/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-05-12 09:41:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.profile.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ResumeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>호핑, 이력서 작성</title>\n");
      out.write("<link href=\"../assets/css/Resume.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"\n");
      out.write("\tintegrity=\"sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"../assets/css/Resume.js\" type=\"text/javascript\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container-resume\">\n");
      out.write("\t\t<div class=\"wrap-resume\">\n");
      out.write("\t\t\t<form class=\"resume-form\" action='write' method='post'>\n");
      out.write("\t\t\t\t<span class=\"resume-form-title\"> 이력서 작성 </span>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"resume name\">\n");
      out.write("\t\t\t\t\t<span class=\"main-name\" name=\"name\">이경진</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"resume info\">\n");
      out.write("\t\t\t\t\t<span class=\"label-tel\">연락처</span> <input type=\"text\" class=\"temp\"\n");
      out.write("\t\t\t\t\t\tname=\"tel\" placeholder=\"010-XXXX-XXXX\"><br /> <span\n");
      out.write("\t\t\t\t\t\tclass=\"label-email\">이메일</span> <input type=\"text\" class=\"temp\"\n");
      out.write("\t\t\t\t\t\tname=\"email\" placeholder=\"hoping@hoping.com\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<span class=\"label\">간단 자기소개</span>\n");
      out.write("\t\t\t\t<div class=\"resume-input1\">\n");
      out.write("\t\t\t\t\t<textarea class=\"input1\" name=\"introduce\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"자기소개글을 작성해주세요. (3~5줄 권장)\"\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 0px; margin-bottom: 0px; height: 120px;\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<span class=\"label\">학력</span>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"resume-input1 select1\">\n");
      out.write("\t\t\t\t\t<button class=\"btnEdu\" type=\"button\">+ 추가</button>\n");
      out.write("\t\t\t\t\t<div class=\"edu\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<span class=\"label\">경력</span>\n");
      out.write("\t\t\t\t<div class=\"resume-input1 select1\">\n");
      out.write("\t\t\t\t\t<button class=\"btnCareer\" type=\"button\">+ 추가</button>\n");
      out.write("\t\t\t\t\t<div class=\"career\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<span class=\"label\">희망 연봉</span>\n");
      out.write("\t\t\t\t<div class=\"resume-input1 select1\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<select class=\"js-select\" name=\"salary\">\n");
      out.write("\t\t\t\t\t\t\t<option>희망연봉을 선택해주세요.</option>\n");
      out.write("\t\t\t\t\t\t\t<option>2000~2500만원</option>\n");
      out.write("\t\t\t\t\t\t\t<option>2500~3000만원</option>\n");
      out.write("\t\t\t\t\t\t\t<option>3000만원이상</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"btn\">\n");
      out.write("\t\t\t\t\t<button class=\"btnTemp\" type=\"button\">임시 저장</button>\n");
      out.write("\t\t\t\t\t<button class=\"btnSubmit\" type=\"submit\">작성 완료</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
