/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-05-12 09:35:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.job.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CompanyList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.83.1\">\r\n");
      out.write("  <title>호핑! 기업소개</title>\r\n");
      out.write("\r\n");
      out.write("  <!--Header CSS-->\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <link href=\"../css/album.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("  <style>\r\n");
      out.write("    .bd-placeholder-img {\r\n");
      out.write("      font-size: 1.125rem;\r\n");
      out.write("      text-anchor: middle;\r\n");
      out.write("      -webkit-user-select: none;\r\n");
      out.write("      -moz-user-select: none;\r\n");
      out.write("      user-select: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (min-width: 768px) {\r\n");
      out.write("      .bd-placeholder-img-lg {\r\n");
      out.write("        font-size: 3.5rem;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:link {\r\n");
      out.write("      color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:visited {\r\n");
      out.write("      color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:active {\r\n");
      out.write("      color: gray;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--header-->\r\n");
      out.write("  <div id=\"site__header\" style=\"font-family: 'Poppins', sans-serif;\">\r\n");
      out.write("    <nav class=\"navbar\" style=\"text-decoration: none; list-style-type: none; color:black\">\r\n");
      out.write("      <div class=\"navbar__logo\" style=\"text-decoration: none; list-style-type: none;\">\r\n");
      out.write("        <a href=\"#\" id=\"header__a\"><b>HOPing</b><b style=\"color: #FFBF00\">.</b></a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"navbar__menu\" id=\"navbar__menu__a\">\r\n");
      out.write("        <li><a href=\"#\"><span>MAIN</span></a></li>\r\n");
      out.write("        <li><a href=\"#\"><span>MAIN</span></a></li>\r\n");
      out.write("        <li><a href=\"#\"><span>MAIN</span></a></li>\r\n");
      out.write("        <li><a href=\"#\"><span>MAIN</span></a></li>\r\n");
      out.write("        <li><a href=\"#\"><span>MAIN</span></a></li>\r\n");
      out.write("        <li class=\"login_out\"><a href=\"#\"><span style=\"font-size: small;\">Login/Bye</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"field\">\r\n");
      out.write("      <ul class=\"choice\">분야</ul>\r\n");
      out.write("      <ul id=\"list\">\r\n");
      out.write("        <li><a href=\"#\">#IT</a></li>\r\n");
      out.write("        <li><a href=\"#\">#교육</a></li>\r\n");
      out.write("        <li><a href=\"#\">#영업</a></li>\r\n");
      out.write("        <li><a href=\"#\">#서비스</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"job\">\r\n");
      out.write("      <ul class=\"choice\">직무</ul>\r\n");
      out.write("      <ul id=\"list\">\r\n");
      out.write("        <li><a href=\"#\">#서울</a></li>\r\n");
      out.write("        <li><a href=\"#\">#강남구</a></li>\r\n");
      out.write("        <li><a href=\"#\">#서비스</a></li>\r\n");
      out.write("        <li><a href=\"#\">#IT</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"album py-5 bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("         <div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col1\">\r\n");
      out.write("         \r\n");
      out.write("            <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \t\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col2\">\r\n");
      out.write("            <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col3\">\r\n");
      out.write("            <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col4\">\r\n");
      out.write("             <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col5\">\r\n");
      out.write("            <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col6\">\r\n");
      out.write("             <div class=\"card shadow-sm\"> \r\n");
      out.write("             <a href=\"#\">\r\n");
      out.write("              <img src=\"../images/samsung.jpg\" style=\"width:350px; height:225px;\" alt=\"\" />\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("              <h2><a href=\"#\">뽑는 분야 </a></h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                <li class=\"com-text\"><a href=\"#\">기업 이름</a></li>\r\n");
      out.write("                <li><a href=\"#\">연봉</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!--\r\n");
      out.write("<footer class=\"text-muted py-5\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <p class=\"float-end mb-1\">\r\n");
      out.write("      <a href=\"#\">Back to top</a>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p class=\"mb-1\">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>\r\n");
      out.write("    <p class=\"mb-0\">New to Bootstrap? <a href=\"/\">Visit the homepage</a> or read our <a href=\"../getting-started/introduction/\">getting started guide</a>.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
